### PR TITLE
created hasura_search_projects

### PR DESCRIPTION
**Pull request by sathya9897**
This file gives the reference on how to use hasura search projects to view all the cloneable projects available on hasura hub through quickstart command.

### CODE REVIEW

**Comment by shahidhk** [comment]
There is already a reference doc on the `search` command: https://docs.hasura.io/0.15/manual/hasuractl/hasura_search.html 

Thanks for the PR, but please go through docs to make sure you are not duplicating efforts 😄

**Comment by sathya9897** [comment]
so the `hasura search` command is only to search for projects, right?

**Comment by shahidhk** [comment]
Yes, only for searching projects available at hasura.io/hub

**Comment by sathya9897** [comment]
But, on running `hasura search` it doesn't show the results of available projects as one would expect. And it takes one and only argument that is `project`. So it doesn't gives the desired output.

**Comment by shahidhk** [comment]
What is the expected behaviour?

**Comment by sathya9897** [comment]
The command in the Hasura CLI is `hasura search` and when a user runs this command he will be expecting that he will be shown a list of hasura projects but that doesn't happen because that command takes one more argument to get that result that is `projects` , so the command to get the projects list becomes `hasura search projects` which will give the desired projects list.

**Comment by shahidhk** [comment]
@sathya9897 `hasura search` is a command to search through all the projects on Hub. `hasura search '*'` will give you all the projects in Hub.

But, what is the use case of getting a list of all projects on Hub?

**Comment by sathya9897** [comment]
@shahidhk `hasura search '*'` or `hasura search projects` both do the same work but my point is to make it `simple to use` as both the commands do only one thing "they fetch the list of hasura projects available".
When i started out with hasura CLI i used the `hasura search` command but it didn't give the results i expected. As the user has to add the extra argument to that command that is `'*'` or `projects` to get the projects list but it is redundant because it will accept only those two arguments which at last give you the same "projects list". Instead we can change/rename those command to just `hasura search` or `hasura search projects` which will give the projects list and where user need not to enter that third argument like `'*'` or `projects`. The second one is better if in future hasura adds some new features to `search` command it will be easy to deal with.

**Comment by coco98** [comment]
@sathya9897 this is the current usage right:

1. `hasura search`: throws an error saying please use as `hasura search <query>` and gives the user an example
2. `hasura search python`: shows a list of python projects

Isn't it very counter intuitive to show the user a bunch of random results when the user does `hasura search`.

I'm not sure what you mean by `hasura search projects`. `hasura search projects` is actually making a search query for the key-word projects and returning several results to you. It's like doing `hasura search hasura` or `hasura search nodejs`. 

@shahidhk Am I clear here?

@sathya9897 When you say that you used hasura CLI initially and tried `hasura search` what did you expect? The command doesn't fetch the list of hasura projects available. It's actually a command to make a search query on hasura.io/hub.

Based on @sathya9897 's comments I understand that the search command is confusing although its behaviour is correct once we know what it does. This is what I propose:

```sh
$ hasura search python

Searching hasura.io/hub for "python"

Showing 1-5 of 23 results...
1. 
2. 
3. 
4. 
5. 
```

I think this makes sense? The current output of the search command is actually quite confusing because I have no idea what it's search and where.

@shahidhk @sathya9897 ?

**Comment by coco98** [comment]
@sathya9897 Just to help you understand, this PR is closed because the documentation for the hasura search docs page is generated programmatically from the hasura CLI code. We'll factor your work in this PR into those docs!

Thanks for the suggestions :)

**Comment by shahidhk** [comment]
Makes sense @coco98

**Comment by sathya9897** [comment]
@shahidhk @coco98 I understood. You got the point. As you gave the example like
`hasura search python`  gives the list of python related projects this should be mentioned in the CLI command example and there should be a section called `available queries` inside of help section which shows the following when someone runs `hasura search --help`

    Available queries:
    ----------------------
    python       list of python projects
    react          list of react projects
    nodejs       list of nodejs projects

**Pull request closed without merging**
